#build dlib wheel from source (https://github.com/davisking/dlib) for windows and ubuntu (python 3.11)
name: dlib
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install setuptools
          pip install cmake
          pip install numpy
          pip install scikit-build
      - name: clone repo
        run: |
          git clone https://github.com/davisking/dlib
      - name: cd dlib
        run: |
          cd dlib
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: dlib
          path: dist/*.whl
